services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - DOCKER_HOST=tcp://dind:2376
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Jenkins to communicate with Docker
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - dind

  dind:
    image: docker:stable-dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind_storage:/var/lib/docker
      - certs:/certs/client
    ports:
      - "2376:2376"

volumes:
  jenkins_home:
  dind_storage:
  certs:

networks:
  jenkins_dind:
    driver: bridge
