services:
  dind:
    image: docker:24.0-dind
    container_name: dind
    user: root
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins-net:
        aliases:
          - docker

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER-CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins-net
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
    depends_on:
      - dind

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:

networks:
  jenkins_net:
    driver: bridge
